server:
  port: 6000

spring:
  application:
    name: august-view-project


  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

