server:
  port: 1000

spring:
  application:
    name: august-eureka
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false # #是否从eureka中拉取注册信息
    register-with-eureka: false # 不需要在自己的注册中心注册
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka