server:
  port: 80

spring:
  application:
    name: august-gateway

  redis:
    host: localhost
    port: 6379
    database: 0

  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 启动 discovery 网关集成,可以实现服务发现
      routes:
       - id: member
         uri: lb://august-authentication
         predicates:
           - Path=/member/**
         filters:


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

exclude:
  auth:
    #不需要授权验证的请求地址,可设置多个,使用逗号分隔开,会跳过AuthFilter授权验证
    path: /member/register,/member/get/phone/code,/member/login,/error

