server:
  port: 4000

spring:
  application:
    name: august-api


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

logging:
  level:
    # feign日志以什么级别监控哪个接口
    xiaozaiyi.crowd*: debug


feign:
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectTimeOut: 100000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 100000
