server:
  port: 80
spring:
  application:
    name: august-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka


zuul:
  ignored-services: "*"
  sensitive-headers: "*"
  routes:
    portal:
      service-id: august-authentication
      path: /**



