server:
  port: 2000

spring:
  application:
    name: august-mysql
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/ssm_crowd?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

mybatis-plus:
  configuration:
    log-prefix: t_
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    xiaozaiyi.crowd.mapper: debug
    xiaozaiyi.crowd.test: debug



