server:
  port: 3000

spring:
  application:
    name: august-redis
  redis:
    host: localhost
    port: 6379
    database: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
