server:
  port: 8009

spring:
  application:
    name: august-pay


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka


feign:
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectTimeOut: 50000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 50000

aliyun:
  pay:
    # 支付宝公钥
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhtXuiSC3H4JevQakd06T9L/KkLaEE767WWfOaFtcW0ove3V6VcZBOUWsU0Tk8JsfTG+WTg5xkRLiDc66SjJE9ljOMGaFUXLqEog1+93uDWe3Vc5q1Oa1YRkN/wpJ2xDeBAzjJ9RV79qMlCvrvuojtYyUD2Djx2O2YntXaoz5dgTgm2hdMb2uEeJQ5jRm1X1QXJEQGeOf9Mw0aF/JRARyV0CyHlmUV3DTfQWSxyG1jOJhazs185f12QElwrL2GLnmkmjutKr6EuU6Cv65ffDmAXgvlBk/O3+XnbPWaemu21L8KStFdHj0RgnCr6dHaiFvf5TT2IgKsTDHUN7GJU9SxwIDAQAB
    app-id: 2021000119691212
    charset: utf-8
    # 支付宝网关
    gateway-url: https://openapi.alipaydev.com/gateway.do
    # 商户私钥，您的PKCS8格式RSA2私钥
    merchant-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCROe5V9EWUzSm4+10LKIovC2RdqrKPOiTecCcvRdFCm7K7fbMhTTAzHJ+9sCIDK2nyZJDth84YXHc/bQONGQwn3e67Mk1BEikt9V8f2blK17LnkLcozaQF3Er1g/D0lTzgcnl3lqihuMLCFyQzjaS3tAz0tWf6Bi8j2G++yLz3cZVGc8IpifGyyk65uaUxFQ2N/K0Dk8hJcCGU0d0dufg+mN9bPN6EDoBxqkcRSY0DgUO59SXkcy6z9b3DhbWw+tHTGe+ykxZHqU1MPWPkxEnEeMr4ESEXm4Ht8QbzrCDVccH7njYapr3XVb9cKyS0qGoEkHrmw0PjFaiQ7wTqwvkZAgMBAAECggEAMUc1BlmS2sEbLTeuBMFG0lvNPLNVT6BtLkVkJnhMX4uxhElM5Tnp5w4JbjY79FNg6e0R+GeimUWW+SCmmdQr+cMm5MJW0IO3EW83Tfl1FF5IyKakX+YXiB2OGe0hb/zL4WU2rkujAO1OuMldcVjY0bT4yHhdxcsfZ8xjbpty84tFLfmz3kom09Dl0Tr9s3/OM2S39HX4uFd5+jFOYwhXr4ox3hRL11Y+9c4/YzhfJFEI3wdoJXGwD5iwJonDA1SmB5od1QKF2+5Rizv+PAd18A7CCFzmSMStw1+k2ZTPZ31b6uGx1vjlOLylOLOVOrDkTB04cnFThWQ5huwIJwcwGQKBgQDbD5G3O+JE71f4arpmpT1ywnzZTgaM2mr0ilxeCNHQN/5KTsEUdKXihahqcU0p/ErvpZghXce0ajwm4Od8Epw615r/edzXNV2JPc5E3tistAalLpUTg0SKL7uy2NXHuWmdyvu9LLFel5B1BkC/bned3XQm5+FnaalUrseTvboXFwKBgQCptxGK0yeO8r2JX6JDmxbsVLWv0yNPTKqqkdLCMRRUmddq46kllVv5Nci/2fw4s+kdz+NHMViZJd5WiwOad3C9YgqhH1AOsYxsHHX3H3UE4ikL5UNuMMY8JUrCz7zxD+mea3btJS8LSTwjkkBX/IN2yuIp9VR/FQUaIHvzFhCPTwKBgQC1XsWhtRYZRyVJy2v7knI28uoVrTFlK24EfA4P2TOGNuX2tg/MlOvHiiwvvRFLYtTUaAF2FsRDDvYwpmNiabIqUdrGDSqYkFmaSK7gfLVfAErENrY9CqET3IOGh1sw2sWkXKxjK37LN6fmDEBNfvPQo8sIb1JDocsODwu0uhA6DwKBgDAjYhFrdTQBvCsj+iWM7wKXwHUfwUsz5tC8zfgQ7cBVZpnF+2tSoyTb0ZZBYV5AAaZYGhJOd9/wstD/W0VMDalaDsPG2vFgAQGFTRyMSqfY8mWSYP73TLMwrLT3MZN6vPwXZUM8ocxkuG8qg5+xWyStxVq7YH0vXCQeBKpdntLXAoGAfYtS7aNAcww2sNCqlFoupMrc/zwdHktb+dXWXuuW4hFTpjtQo0F7B5f70SymAqbga0ErNXa93q/zfFNpiPgx4WLzsZNlFblm3YZZLD/zST5aX5aAtJZKQYX1L3yTVeAJ82DjT4jD5+y5f5xNaUL4lLB7bYdaLry5AEBXz/jCQtM=
    notify-url: http://localhost:80/payorder/notify
    # 页面跳转同步通知页面路径
    return-url: http://localhost:8001/payorder/return
    # 签名方式
    sign-type: RSA2
    # 支付宝网关
    log-path: "D:\\"
    format: "json"
